# Generated by Django 5.1.7 on 2025-03-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('ferme', models.BooleanField(default=True)),
                ('ouverture', models.TimeField(blank=True, null=True)),
                ('fermeture', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
