# Generated by Django 5.1.7 on 2026-09-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_horairespecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDayLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
