# Generated by Django 5.1.7 on 2026-09-28 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Restaurant Osaka', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('public_phone', models.CharField(blank=True, max_length=30)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('capacity', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('reservation_duration_minutes', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(30)])),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)])),
                ('modification_cutoff_hours', models.PositiveSmallIntegerField(default=2)),
                ('max_online_party_size', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'configuration du restaurant',
                'verbose_name_plural': 'configuration du restaurant',
            },
        ),
        migrations.CreateModel(
            name='WeeklyOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
            ],
            options={
                'verbose_name': 'horaire hebdomadaire',
                'verbose_name_plural': 'horaires hebdomadaires',
                'ordering': ('weekday', 'opens_at'),
                'constraints': [models.UniqueConstraint(fields=('weekday', 'opens_at', 'closes_at'), name='unique_weekly_service')],
            },
        ),
    ]
