# Generated by Django 5.1.7 on 2026-09-28 13:15

from django.db import migrations, models


def copy_legacy_special_hours(apps, schema_editor):
    LegacyHours = apps.get_model('reservations', 'HoraireSpecial')
    SpecialHours = apps.get_model('restaurant', 'SpecialOpeningHours')

    for legacy in LegacyHours.objects.all().iterator():
        SpecialHours.objects.update_or_create(
            date=legacy.date,
            defaults={
                'closed': legacy.ferme,
                'opens_at': legacy.ouverture,
                'closes_at': legacy.fermeture,
                'description': legacy.description,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('reservations', '0002_horairespecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('closed', models.BooleanField(default=True)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'horaire exceptionnel',
                'verbose_name_plural': 'horaires exceptionnels',
                'ordering': ('date',),
            },
        ),
        migrations.RunPython(
            copy_legacy_special_hours,
            migrations.RunPython.noop,
        ),
    ]
