# Generated by Django 5.1.7 on 2025-04-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_allergene_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPromotionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('plat_associe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_associes', to='menu.plat')),
                ('plat_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_principal', to='menu.plat')),
            ],
        ),
    ]
