# Generated by Django 5.1.7 on 2026-09-27 19:40

from django.db import migrations, models


def rename_known_duplicate_promotions(apps, schema_editor):
    MenuPromotionnel = apps.get_model('menu', 'MenuPromotionnel')
    replacements = {
        2: 'Menu Dragon Roll',
        4: 'Menu Futomaki',
    }

    for promotion_id, new_name in replacements.items():
        MenuPromotionnel.objects.filter(
            pk=promotion_id,
            nom='SHI',
        ).update(nom=new_name)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menupromotionnel'),
    ]

    operations = [
        migrations.RunPython(
            rename_known_duplicate_promotions,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='menupromotionnel',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
